import { FilterDefinition, FilterId } from '../types';

export const PHOTO_FILTERS: FilterDefinition[] = [
  {
    id: 'normal',
    name: 'Natural',
    tagline: 'Clean & fresh',
    emoji: '🌿',
    cssFilter: 'none',
    canvasFilter: 'none',
  },
  {
    id: 'pink_bubblegum',
    name: 'Bubblegum',
    tagline: 'Sweet strawberry pop',
    emoji: '🎀',
    cssFilter: 'contrast(1.08) saturate(1.35) brightness(1.06) hue-rotate(-8deg)',
    overlayStyle: 'bg-pink-400/10 mix-blend-color',
    overlayColor: 'rgba(244, 114, 182, 0.12)',
    overlayBlendMode: 'color',
    canvasFilter: 'contrast(108%) saturate(135%) brightness(106%) hue-rotate(-8deg)',
  },
  {
    id: 'dreamy_soft',
    name: 'Dreamy Fairy',
    tagline: 'Soft bloom & glow',
    emoji: '☁️',
    cssFilter: 'brightness(1.1) contrast(0.92) saturate(1.15)',
    overlayStyle: 'bg-rose-200/15 mix-blend-screen',
    overlayColor: 'rgba(254, 205, 211, 0.18)',
    overlayBlendMode: 'screen',
    canvasFilter: 'brightness(110%) contrast(92%) saturate(115%)',
  },
  {
    id: 'tokyo_harajuku',
    name: 'Harajuku Pop',
    tagline: 'Vibrant kawaii tones',
    emoji: '🍡',
    cssFilter: 'saturate(1.5) contrast(1.15) brightness(1.05)',
    overlayStyle: 'bg-fuchsia-300/10 mix-blend-overlay',
    overlayColor: 'rgba(240, 171, 252, 0.12)',
    overlayBlendMode: 'overlay',
    canvasFilter: 'saturate(150%) contrast(115%) brightness(105%)',
  },
  {
    id: 'film_90s',
    name: '90s Disposable',
    tagline: 'Warm vintage film',
    emoji: '📸',
    cssFilter: 'sepia(0.2) contrast(1.18) saturate(1.1) brightness(0.98)',
    overlayStyle: 'bg-amber-500/8 mix-blend-multiply',
    overlayColor: 'rgba(245, 158, 11, 0.08)',
    overlayBlendMode: 'multiply',
    canvasFilter: 'sepia(20%) contrast(118%) saturate(110%) brightness(98%)',
  },
  {
    id: 'sparkle_blush',
    name: 'Kira Blush',
    tagline: 'Rosy cheeks & glow',
    emoji: '✨',
    cssFilter: 'brightness(1.08) contrast(1.05) saturate(1.22)',
    overlayStyle: 'bg-rose-400/12 mix-blend-soft-light',
    overlayColor: 'rgba(251, 113, 133, 0.14)',
    overlayBlendMode: 'soft-light',
    canvasFilter: 'brightness(108%) contrast(105%) saturate(122%)',
  },
  {
    id: 'sweet_peach',
    name: 'Sweet Peach',
    tagline: 'Warm apricot sunshine',
    emoji: '🍑',
    cssFilter: 'sepia(0.12) saturate(1.3) contrast(1.05) brightness(1.08)',
    overlayStyle: 'bg-orange-300/12 mix-blend-screen',
    overlayColor: 'rgba(253, 186, 116, 0.14)',
    overlayBlendMode: 'screen',
    canvasFilter: 'sepia(12%) saturate(130%) contrast(105%) brightness(108%)',
  },
  {
    id: 'vintage_rose',
    name: 'Rose Romance',
    tagline: 'Nostalgic mauve pastel',
    emoji: '🌹',
    cssFilter: 'sepia(0.35) hue-rotate(300deg) contrast(1.08) brightness(1.02)',
    overlayStyle: 'bg-pink-600/10 mix-blend-color-dodge',
    overlayColor: 'rgba(219, 39, 119, 0.10)',
    overlayBlendMode: 'screen',
    canvasFilter: 'sepia(35%) hue-rotate(300deg) contrast(108%) brightness(102%)',
  },
  {
    id: 'cyber_y2k',
    name: 'Cyber Y2K',
    tagline: 'Glossy retro digital',
    emoji: '🪩',
    cssFilter: 'contrast(1.25) saturate(1.4) hue-rotate(15deg) brightness(1.02)',
    overlayStyle: 'bg-cyan-300/10 mix-blend-color-burn',
    overlayColor: 'rgba(103, 232, 249, 0.10)',
    overlayBlendMode: 'overlay',
    canvasFilter: 'contrast(125%) saturate(140%) hue-rotate(15deg) brightness(102%)',
  },
  {
    id: 'classic_noir',
    name: 'Velvet Noir',
    tagline: 'Romantic B&W',
    emoji: '🖤',
    cssFilter: 'grayscale(1) contrast(1.22) brightness(1.04)',
    overlayStyle: 'bg-pink-100/10 mix-blend-screen',
    overlayColor: 'rgba(255, 228, 230, 0.08)',
    overlayBlendMode: 'screen',
    canvasFilter: 'grayscale(100%) contrast(122%) brightness(104%)',
  },
  {
    id: 'digicam_2000',
    name: 'Digicam 2000s',
    tagline: 'Sony Cybershot flash',
    emoji: '📷',
    cssFilter: 'contrast(1.28) brightness(1.12) saturate(1.22) hue-rotate(-6deg)',
    overlayStyle: 'bg-cyan-200/12 mix-blend-overlay',
    overlayColor: 'rgba(165, 243, 252, 0.12)',
    overlayBlendMode: 'overlay',
    canvasFilter: 'contrast(128%) brightness(112%) saturate(122%) hue-rotate(-6deg)',
  },
  {
    id: 'grainy_vintage_35mm',
    name: 'Grainy 35mm',
    tagline: 'Kodak disposable film',
    emoji: '🎞️',
    cssFilter: 'sepia(0.32) contrast(1.2) saturate(1.25) brightness(0.96) hue-rotate(-12deg)',
    overlayStyle: 'bg-amber-600/10 mix-blend-multiply',
    overlayColor: 'rgba(217, 119, 6, 0.10)',
    overlayBlendMode: 'multiply',
    canvasFilter: 'sepia(32%) contrast(120%) saturate(125%) brightness(96%) hue-rotate(-12deg)',
  },
  {
    id: 'y2k_cyber_pink',
    name: 'Cyber Pink Y2K',
    tagline: 'Glossy neon magenta',
    emoji: '💖',
    cssFilter: 'contrast(1.35) saturate(1.55) brightness(1.05) hue-rotate(12deg)',
    overlayStyle: 'bg-fuchsia-500/14 mix-blend-color-dodge',
    overlayColor: 'rgba(217, 70, 239, 0.14)',
    overlayBlendMode: 'screen',
    canvasFilter: 'contrast(135%) saturate(155%) brightness(105%) hue-rotate(12deg)',
  },
  {
    id: 'digicam_flash',
    name: 'Night Flash',
    tagline: 'Direct camera flash pop',
    emoji: '⚡',
    cssFilter: 'contrast(1.36) brightness(1.16) saturate(1.3)',
    overlayStyle: 'bg-white/10 mix-blend-soft-light',
    overlayColor: 'rgba(255, 255, 255, 0.12)',
    overlayBlendMode: 'soft-light',
    canvasFilter: 'contrast(136%) brightness(116%) saturate(130%)',
  },
  {
    id: 'vintage_gal_purikura',
    name: 'Shibuya Gyaru',
    tagline: '2000s Gal purikura glow',
    emoji: '🌸',
    cssFilter: 'brightness(1.18) contrast(1.05) saturate(1.35) hue-rotate(-10deg)',
    overlayStyle: 'bg-rose-300/18 mix-blend-screen',
    overlayColor: 'rgba(253, 164, 175, 0.18)',
    overlayBlendMode: 'screen',
    canvasFilter: 'brightness(118%) contrast(105%) saturate(135%) hue-rotate(-10deg)',
  },
  {
    id: 'retro_vhs_tape',
    name: 'VHS Camcorder',
    tagline: '90s analog tape vibe',
    emoji: '📼',
    cssFilter: 'contrast(1.22) saturate(1.4) brightness(1.04) sepia(0.2) hue-rotate(345deg)',
    overlayStyle: 'bg-violet-400/10 mix-blend-overlay',
    overlayColor: 'rgba(167, 139, 250, 0.10)',
    overlayBlendMode: 'overlay',
    canvasFilter: 'contrast(122%) saturate(140%) brightness(104%) sepia(20%) hue-rotate(345deg)',
  },
  {
    id: 'grainy_lofi',
    name: 'Lofi Grain',
    tagline: 'Dreamy matte nostalgia',
    emoji: '📻',
    cssFilter: 'contrast(1.1) brightness(1.06) saturate(0.92) sepia(0.18)',
    overlayStyle: 'bg-stone-300/12 mix-blend-multiply',
    overlayColor: 'rgba(214, 211, 209, 0.12)',
    overlayBlendMode: 'multiply',
    canvasFilter: 'contrast(110%) brightness(106%) saturate(92%) sepia(18%)',
  },
  {
    id: 'grainy_noir',
    name: 'Grainy Noir',
    tagline: 'Gritty street monochrome',
    emoji: '🎬',
    cssFilter: 'grayscale(1) contrast(1.42) brightness(0.98)',
    overlayStyle: 'bg-zinc-900/10 mix-blend-color-burn',
    overlayColor: 'rgba(24, 24, 27, 0.10)',
    overlayBlendMode: 'multiply',
    canvasFilter: 'grayscale(100%) contrast(142%) brightness(98%)',
  },
  {
    id: 'dreamy_angel_aura',
    name: 'Angel Aura',
    tagline: 'Ethereal hazy soft bloom',
    emoji: '🪽',
    cssFilter: 'brightness(1.18) contrast(0.86) saturate(1.18) hue-rotate(5deg)',
    overlayStyle: 'bg-gradient-to-tr from-pink-200/20 via-purple-100/15 to-yellow-100/15 mix-blend-screen',
    overlayColor: 'rgba(254, 205, 211, 0.22)',
    overlayBlendMode: 'screen',
    canvasFilter: 'brightness(118%) contrast(86%) saturate(118%) hue-rotate(5deg)',
  },
  {
    id: 'faded_polaroid',
    name: 'Faded Polaroid',
    tagline: 'Milky washed matte film',
    emoji: '📸',
    cssFilter: 'contrast(0.85) brightness(1.1) sepia(0.24) saturate(0.94)',
    overlayStyle: 'bg-amber-100/15 mix-blend-screen',
    overlayColor: 'rgba(254, 243, 199, 0.16)',
    overlayBlendMode: 'screen',
    canvasFilter: 'contrast(85%) brightness(110%) sepia(24%) saturate(94%)',
  },
  {
    id: 'milky_lavender_haze',
    name: 'Lavender Haze',
    tagline: 'Dreamy twilight purple mist',
    emoji: '💜',
    cssFilter: 'brightness(1.15) contrast(0.88) saturate(1.24) hue-rotate(24deg)',
    overlayStyle: 'bg-purple-300/18 mix-blend-screen',
    overlayColor: 'rgba(216, 180, 254, 0.20)',
    overlayBlendMode: 'screen',
    canvasFilter: 'brightness(115%) contrast(88%) saturate(124%) hue-rotate(24deg)',
  },
  {
    id: 'faded_blush_matte',
    name: 'Matte Blush',
    tagline: 'Soft washed vintage pink',
    emoji: '🌸',
    cssFilter: 'contrast(0.84) brightness(1.14) saturate(1.14) hue-rotate(-8deg)',
    overlayStyle: 'bg-rose-200/20 mix-blend-screen',
    overlayColor: 'rgba(254, 205, 211, 0.22)',
    overlayBlendMode: 'screen',
    canvasFilter: 'contrast(84%) brightness(114%) saturate(114%) hue-rotate(-8deg)',
  },
  {
    id: 'cloud_nine_mist',
    name: 'Cloud Nine',
    tagline: 'Angelic soft focus radiance',
    emoji: '☁️',
    cssFilter: 'brightness(1.22) contrast(0.82) saturate(1.08)',
    overlayStyle: 'bg-white/20 mix-blend-screen',
    overlayColor: 'rgba(255, 255, 255, 0.24)',
    overlayBlendMode: 'screen',
    canvasFilter: 'brightness(122%) contrast(82%) saturate(108%)',
  },
  {
    id: 'vintage_peach_glow',
    name: 'Peach Sunset Glow',
    tagline: 'Golden hour pastel haze',
    emoji: '🍑',
    cssFilter: 'brightness(1.12) contrast(0.88) saturate(1.3) sepia(0.18) hue-rotate(350deg)',
    overlayStyle: 'bg-orange-200/18 mix-blend-screen',
    overlayColor: 'rgba(254, 215, 170, 0.18)',
    overlayBlendMode: 'screen',
    canvasFilter: 'brightness(112%) contrast(88%) saturate(130%) sepia(18%) hue-rotate(350deg)',
  },
  {
    id: 'ethereal_moonlight',
    name: 'Moonlit Haze',
    tagline: 'Dreamy cool silver-blue fairy glow',
    emoji: '🌙',
    cssFilter: 'brightness(1.1) contrast(0.88) saturate(1.08) hue-rotate(185deg)',
    overlayStyle: 'bg-cyan-200/16 mix-blend-screen',
    overlayColor: 'rgba(165, 243, 252, 0.18)',
    overlayBlendMode: 'screen',
    canvasFilter: 'brightness(110%) contrast(88%) saturate(108%) hue-rotate(185deg)',
  },
];

export const getFilterById = (id: FilterId): FilterDefinition => {
  return PHOTO_FILTERS.find((f) => f.id === id) || PHOTO_FILTERS[0];
};
