import { FrameOption } from '../types';

export const FRAME_OPTIONS: FrameOption[] = [
  // --- Cute Pastels ---
  {
    id: 'soft_pink',
    name: 'Baby Pink',
    bgClass: 'bg-pink-100 border-pink-200',
    textColor: 'text-pink-600',
    borderColor: '#fbcfe8',
    accentColor: '#f43f5e',
    canvasBg: '#fce7f3',
  },
  {
    id: 'strawberry_milk',
    name: 'Strawberry Milk',
    bgClass: 'bg-rose-50 border-rose-200',
    textColor: 'text-rose-500',
    borderColor: '#fecdd3',
    accentColor: '#fb7185',
    canvasBg: '#fff1f2',
  },
  {
    id: 'cherry_blossom',
    name: 'Sakura Petal',
    bgClass: 'bg-gradient-to-b from-pink-200 via-rose-100 to-pink-200 border-pink-300',
    textColor: 'text-pink-700',
    borderColor: '#f472b6',
    accentColor: '#e11d48',
    canvasBg: '#fbcfe8',
  },
  {
    id: 'checker_pink',
    name: 'Y2K Checker',
    bgClass: 'bg-pink-300 border-pink-400',
    textColor: 'text-pink-900',
    borderColor: '#f472b6',
    accentColor: '#ec4899',
    canvasBg: '#f9a8d4',
  },
  {
    id: 'holographic',
    name: 'Pearl Shimmer',
    bgClass: 'bg-gradient-to-tr from-pink-200 via-purple-100 to-teal-100 border-pink-200',
    textColor: 'text-purple-600',
    borderColor: '#e9d5ff',
    accentColor: '#c084fc',
    canvasBg: '#f3e8ff',
  },
  {
    id: 'coquette_bows',
    name: 'Coquette Rose',
    bgClass: 'bg-pink-500 border-pink-600',
    textColor: 'text-white',
    borderColor: '#ec4899',
    accentColor: '#fff',
    canvasBg: '#ec4899',
  },
  {
    id: 'pastel_lilac',
    name: 'Pastel Lilac',
    bgClass: 'bg-purple-100 border-purple-200',
    textColor: 'text-purple-600',
    borderColor: '#e9d5ff',
    accentColor: '#a855f7',
    canvasBg: '#f3e8ff',
  },
  {
    id: 'retro_polaroid',
    name: 'Classic White',
    bgClass: 'bg-white border-slate-200 shadow-sm',
    textColor: 'text-slate-800',
    borderColor: '#e2e8f0',
    accentColor: '#0f172a',
    canvasBg: '#ffffff',
  },

  // --- Dark Girly & Coquette Colors ---
  {
    id: 'midnight_cherry',
    name: 'Midnight Cherry',
    bgClass: 'bg-[#18030a] border-[#f43f5e] shadow-lg',
    textColor: 'text-rose-200',
    borderColor: '#f43f5e',
    accentColor: '#fb7185',
    canvasBg: '#18030a',
  },
  {
    id: 'goth_velvet_black',
    name: 'Goth Velvet',
    bgClass: 'bg-[#0e0d13] border-[#f472b6] shadow-lg',
    textColor: 'text-pink-200',
    borderColor: '#ec4899',
    accentColor: '#f472b6',
    canvasBg: '#0e0d13',
  },
  {
    id: 'dark_berry_wine',
    name: 'Berry Wine',
    bgClass: 'bg-[#220718] border-[#db2777] shadow-lg',
    textColor: 'text-pink-200',
    borderColor: '#be185d',
    accentColor: '#f472b6',
    canvasBg: '#220718',
  },
  {
    id: 'midnight_sparkle',
    name: 'Midnight Cyber',
    bgClass: 'bg-[#120a1f] border-[#c084fc] shadow-lg',
    textColor: 'text-purple-200',
    borderColor: '#c084fc',
    accentColor: '#e879f9',
    canvasBg: '#120a1f',
  },
  {
    id: 'dark_leopard_noir',
    name: 'Dark Cheetah',
    bgClass: 'bg-[#1a1016] border-[#be185d] shadow-lg',
    textColor: 'text-pink-300',
    borderColor: '#be185d',
    accentColor: '#f472b6',
    canvasBg: '#1a1016',
  },
  {
    id: 'espresso_rose',
    name: 'Espresso Rose',
    bgClass: 'bg-[#24151c] border-[#fb7185] shadow-lg',
    textColor: 'text-rose-200',
    borderColor: '#fb7185',
    accentColor: '#fda4af',
    canvasBg: '#24151c',
  },
  {
    id: 'dark_emerald_coquette',
    name: 'Emerald Velvet',
    bgClass: 'bg-[#0a1a12] border-[#f472b6] shadow-lg',
    textColor: 'text-pink-200',
    borderColor: '#f472b6',
    accentColor: '#fbcfe8',
    canvasBg: '#0a1a12',
  },
  {
    id: 'vampire_lace',
    name: 'Vampire Ruby',
    bgClass: 'bg-[#2b050d] border-[#e11d48] shadow-lg',
    textColor: 'text-rose-200',
    borderColor: '#f43f5e',
    accentColor: '#fda4af',
    canvasBg: '#2b050d',
  },
  {
    id: 'mauve_twilight',
    name: 'Mauve Twilight',
    bgClass: 'bg-[#2c142d] border-[#e879f9] shadow-lg',
    textColor: 'text-fuchsia-200',
    borderColor: '#e879f9',
    accentColor: '#f0abfc',
    canvasBg: '#2c142d',
  },
];

export const getFrameById = (id: string): FrameOption => {
  return FRAME_OPTIONS.find((f) => f.id === id) || FRAME_OPTIONS[0];
};
